### ISSUE TITLE
Support . in branch names

### ISSUE THREAD

**Issue by Auo** [jonschlinkert/parse-git-config#8]
replicate:
create a branch named "2.0"

```javascript
...
'branch "master"': { remote: 'origin', merge: 'refs/heads/master' },
  'branch "2': { '0"': { remote: 'origin', merge: 'refs/heads/2.0' }
...
```

Expected result would be "2.0"

**Comment by jonschlinkert** [comment]
I just confirmed that this bug is caused by the [ini](https://www.npmjs.com/package/ini) library. It appears that `ini` allows keys to be escaped, like `2\\.0`, but with git config idk how users would actually be able to do that in most cases, so I went ahead and added a fix to this lib. I'll push it up in a few.
